Massive code remake
karbofos22/Space-Defender pull request #1
Opened 2022-12-11 13:43 UTC by karbofos22

Got rid of almost all lines of GameObject.Find, split massive scripts into smaller ones to better control the mechanics.

The following templates have been implemented:
DI (via Zenject asset)
Observer (using the UnityEvent system)

Not much DI is introduced, only there it is needed (object pooler for player, player for spawned bonuses). Much more of an observer to control gameplay and break dependencies.

2022-12-12 13:51 UTC, DanMagor requested changes

2022-12-12 13:51 UTC, DanMagor commented on Assets/Scripts/EnemyScripts/BeeBoss/BeeBossBehaviour.cs
> +    public ParticleSystem bloodParticle;
тут забыл на private поменять или здесь надо public?

2022-12-12 13:51 UTC, DanMagor commented on Assets/Scripts/EnemyScripts/BeeBoss/BeeBossBehaviour.cs
> +    private readonly int immortality = 1000000;
Если остаешься на такой логике и хочешь оставить проект в портфолио - напиши коммент, что для простоты бессмертие сделано через большое количество ХП (на английском)

2022-12-12 13:51 UTC, DanMagor commented on Assets/Scripts/EnemyScripts/BeeBoss/BeeBossBehaviour.cs
> +    public int Hp
По факту, ты все еще можешь менять HP снаружи, точно так должно быть? Не Private set?

2022-12-12 13:51 UTC, DanMagor commented on Assets/Scripts/EnemyScripts/BeeBoss/BeeBossBehaviour.cs
> +        ScoreValue = 20000;
Magic Numbers

2022-12-12 13:51 UTC, DanMagor commented on Assets/Scripts/EnemyScripts/BeeBoss/BeeBossBehaviour.cs
> +        GlobalEventManager.BossFight.AddListener(() =>
Я бы положил логику внутри в отдельный метод инициализации.

Или внутри Start сделал бы GlobalEventManager.BossFight.AddListener(PrimarySetup)

2022-12-12 13:51 UTC, DanMagor commented on Assets/Scripts/EnemyScripts/BeeBoss/BeeBossBehaviour.cs
> +        if (other.CompareTag("Projectile"))
От тегов надо тоже избавляться

2022-12-12 13:51 UTC, DanMagor commented on Assets/Scripts/EnemyScripts/BeeBoss/BeeBossBehaviour.cs
> +        if (Hp < 500)
magic numbers

2022-12-12 13:51 UTC, DanMagor commented on Assets/Scripts/EnemyScripts/BeeBoss/BeeBossBehaviour.cs
> +        GlobalEventManager.BossFight.AddListener(() =>
У тебя тут проблемка. Ты подписываешься добавляя Listener, но не отписываешься. Это может привести к некоррктному вызову ивентов. У тебя всегда должна быть отписка, вместе с подпиской. Лучше делай подписку на OnEnable, а отписку на OnDisable и логика инициализации в PrimarySetup

2022-12-12 13:51 UTC, DanMagor commented on Assets/Scripts/EnemyScripts/BeeBoss/BeeBossMovement.cs
> +    Vector3 StrafeByX()
Тут модификаторы забыл Private

2022-12-12 13:51 UTC, DanMagor commented on Assets/Scripts/EnemyScripts/BeeBoss/BeeBossMovement.cs
> +        return v;
v - обычно это скорость, а ты вроде позицию возвращаешь

2022-12-12 13:51 UTC, DanMagor commented on Assets/Scripts/EnemyScripts/BeeBoss/BeeBossMovement.cs
> +        if (transform.position == stopPoint)
Вот тут такой Point - при движении точки могут не идеально сходиться. Поэтому обычно делаеют (transform.position - stopPoint).magnitude <= eps;
где eps = 0.01, или еще какой-то мелкой цифре. Float числа могут просто не сойтись у тебя при движении

2022-12-12 13:51 UTC, DanMagor commented on Assets/Scripts/EnemyScripts/BeeBoss/BeeBossMovement.cs
> +            GlobalEventManager.SendBossFight();
Это выглядит так, что пчелла управляет всей игрой через GlobalEventManager, так тоже не совсем правильно

2022-12-12 13:51 UTC, DanMagor commented on Assets/Scripts/EnemyScripts/BeeBoss/BeeBossShooting.cs
> +    public bool laserRayActive;
public?

2022-12-12 13:51 UTC, DanMagor commented on Assets/Scripts/EnemyScripts/BeeBoss/BeeBossShooting.cs
> +        AddGameOverListener();
Тут таже проблема с подпиской и отпиской

2022-12-13 13:23 UTC, karbofos22 commented on Assets/Scripts/EnemyScripts/BeeBoss/BeeBossBehaviour.cs
> +    private readonly int immortality = 1000000;
добавил коммент

2022-12-13 13:23 UTC, karbofos22 commented on Assets/Scripts/EnemyScripts/BeeBoss/BeeBossBehaviour.cs
> +    public ParticleSystem bloodParticle;
Верно, прошляпил. Исправлено.

2022-12-13 13:44 UTC, karbofos22 commented on Assets/Scripts/EnemyScripts/BeeBoss/BeeBossBehaviour.cs
> +    public int Hp
Согласен, логика ошибочна. Исправил.

2022-12-13 13:46 UTC, karbofos22 commented on Assets/Scripts/EnemyScripts/BeeBoss/BeeBossBehaviour.cs
> +        ScoreValue = 20000;
Исправил

2022-12-13 14:03 UTC, karbofos22 commented on Assets/Scripts/EnemyScripts/BeeBoss/BeeBossMovement.cs
> +        return v;
Переименовал

2022-12-13 14:03 UTC, karbofos22 commented on Assets/Scripts/EnemyScripts/BeeBoss/BeeBossMovement.cs
> +    Vector3 StrafeByX()
Добавил

2022-12-13 14:09 UTC, karbofos22 commented on Assets/Scripts/EnemyScripts/BeeBoss/BeeBossMovement.cs
> +        if (transform.position == stopPoint)
Учту. Условие исправил

2022-12-13 14:32 UTC, karbofos22 commented on Assets/Scripts/EnemyScripts/BeeBoss/BeeBossBehaviour.cs
> +        GlobalEventManager.BossFight.AddListener(() =>
Перенес в Start строчку GlobalEventManager.BossFight.AddListener(PrimarySetup)
В методе PrimarySetup добавил отписку. Про Enable/Disable учту, но не совсем применимо в текущем случае.

2022-12-13 14:32 UTC, karbofos22 commented on Assets/Scripts/EnemyScripts/BeeBoss/BeeBossBehaviour.cs
> +        if (Hp < 500)
Исправил

2022-12-13 14:32 UTC, karbofos22 commented on Assets/Scripts/EnemyScripts/BeeBoss/BeeBossMovement.cs
> +            GlobalEventManager.SendBossFight();
Переименовал эвент

2022-12-13 14:48 UTC, karbofos22 commented on Assets/Scripts/EnemyScripts/BeeBoss/BeeBossShooting.cs
> +    public bool laserRayActive;
Исправил.

2022-12-13 14:51 UTC, karbofos22 commented on Assets/Scripts/EnemyScripts/BeeBoss/BeeBossShooting.cs
> +        AddGameOverListener();
Исправил.

2022-12-13 16:36 UTC, karbofos22 commented on Assets/Scripts/EnemyScripts/BeeBoss/BeeBossBehaviour.cs
> +        if (other.CompareTag("Projectile"))
Заменил где возможно на GetComponent<>. Там где пришлось бы перелопачивать, оставил.

2023-01-13 10:12 UTC, merged